name: Website
on:
  push:
    branches: [master]
jobs:
  job1:
    name: Build Website
    runs-on: ubuntu-latest

    steps:
    - uses: actions/cache@v2
      with:
        path: /tmp/hugo_cache
        key: ${{ runner.os }}-hugomod-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-hugomod-
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
          node-version: 12.x

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'

    - name: Prepare
      run: |
        cd docs
        npm i fs-extra properties
        node parse.js
        hugo --minify

    - name: Publish
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/public